kubernetes/cray-opa/templates/_policy-ingressgateway.tpl

Fix an instance of the WLM workload that used ncn instead of compute.
* Found while testing PE-37952
No known risks
- [n/a ] Version number(s) incremented, if applicable
- [n/a ] Copyrights updated
- [x ] License file intact
- [x ] Target branch correct
- [n/a ] CHANGELOG.md updated
- [x ] Testing is appropriate and complete, if applicable
- [n/a ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

PE-37952 Fix typo in WLM workload

---

kubernetes/cray-opa/CHANGELOG.md
kubernetes/cray-opa/Chart.yaml

Releasing cray-opa version 1.3.0 for CSM 1.2
* Resolves [CASMCMS-7355](https://connect.us.cray.com/jira/browse/CASMCMS-7355)
* Resolves [CASMPET-3940](https://connect.us.cray.com/jira/browse/CASMPET-3940)
* Resolves [CASMPET-4141](https://connect.us.cray.com/jira/browse/CASMPET-4141)
* Resolves [CASMPET-5150](https://connect.us.cray.com/jira/browse/CASMPET-5150)
* Resolves [PE-37951](https://connect.us.cray.com/jira/browse/PE-37951)

Bump cray-opa to 1.3.0

---

.github/workflows/charts-lint-test-scan-cron.yml
.github/workflows/charts-lint-test-scan.yml
kubernetes/.snyk
kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/deployment.yaml
kubernetes/cray-opa/templates/envoyfilter.yaml
kubernetes/cray-opa/tests/opa/Dockerfile
kubernetes/cray-opa/values.yaml

Followed the objectives in CASM-2670. The only image in this
repository is opa. That was referenced from docker.io and is now
using the image that's build from the container-images repository.
IS THIS A NEW FEATURE OR CRITICAL BUG FIX? new feature
DOES THIS CHANGE INVOLVE ANY SCHEME CHANGES?  N
REMINDER: HAVE YOU INCREMENTED VERSION NUMBERS? Y
REMINDER 2: HAVE YOU UPDATED THE COPYRIGHT PER hpe GUIDELINES: Copyright 2014-2021 Hewlett Packard Enterprise Development LP    ? N/A
* Resolves CASMPET-5036
Tested on:
Were the install/upgrade based validation checks/tests run?(goss tests/install-validation doc) N
Was a fresh Install tested? Y
Was an Upgrade tested?      Y
Was a Downgrade tested?     Y
If schema changes were part of this change, how were those handled in your …

CASMPET-5036: Update image refs in Helm charts

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/values.yaml

This disabled the xname validation by default. We won't be enabling them by default until we're sure it will work without a performance hit. The version is being bumped as this will be released as soon as it's merged.
* Resolves [CASMPET-5187](https://connect.us.cray.com/jira/browse/CASMINST-5187)
The enable/disable was tested when the option was added and a retest to disable the functionality is not needed.
None

CASMPET-5187 Disable xname validation by default

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/deployment.yaml
kubernetes/cray-opa/values.yaml

This change allows us to choose whether to use required or preferred anti affinity. Preferred is needed on vshasta. On systems with 4 or more worker nodes, required should be used.
* Resolves [CASMINST-4007](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4007) 
Validated anti affinity rules worked with both toggles and that they functioned correctly.
- Were continuous integration tests run? Y
- Was upgrade tested? Y
- Was downgrade tested? Y

CASMINST-4007 Update anti affinity support.

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-admin_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-admin_policy_xforward_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-user_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-user_policy_xforward_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.xname_workloads.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_xforward_test.rego.tpl
kubernetes/cray-opa/values.yaml

Disabled exposing spire-jwks externally and switched the jwks endpoint opa uses to the internal URL.
* Resolves [CASMINST-3979](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3979) 
Validated that spire tokens kept working after the upgrade and failed if the spire-jwks service was scaled down to 0.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N/A
If cray-opa gets downgraded to 1.9.0, spire also needs to be downgraded to 2.3.1 in order to create the spire-jwks VirtualService.

CASMINST-3979 Disable external spire-jwks access

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-admin.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-user.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-admin_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-admin_policy_xforward_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-user_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-user_policy_xforward_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.xname_workloads.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_xforward_test.rego.tpl

remove the BulkSoftwareStatus path that was relied on by DVS.
Should go with CSM 1.2.6
* Resolves CASMHMS-4961
* build system
Ran `make`; builds passed.

Casmhms 4961 master

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-admin_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-admin_policy_xforward_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-user_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-user_policy_xforward_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.xname_workloads.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_xforward_test.rego.tpl

remove the BulkSoftwareStatus path that was relied on by DVS.
Should go with CSM 1.2.6
* Resolves CASMHMS-4961
* build system
Ran `make`; builds passed.

Casmhms 4961

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/templates/deployment.yaml
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.xname_workloads.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_xforward_test.rego.tpl
kubernetes/cray-opa/values.yaml

This sets anti-affinity to preferred so that the opa pods don't get stuck trying to be replaced during a deployment on a 3 worker cluster.
Due to there not being an easy, clean way to roll back to 1.10.1, the 1.10.1 chart was copied over the 1.10.0 release/csm-1.2 chart. The only change from 1.10.1 to 1.10.5 is changing required to preferred.
This also bumps the chart to 1.10.5 to avoid having it conflict with chart versions created for CSM 1.2.6.
* Partially Resolves [CASMINST-4757](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4757)
Validated upgrades could occur without the pods getting stuck
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N
- Were continuous integration tests run? If not, why? Y 
- Was upgrade …

casminst-4757 Set anti affinity to preferred

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/deployment.yaml

Adds UUID and pod disruption policies to allow us to use requiredDuringSchedulingIgnoredDuringExecution pod anti affinity policies without causing upgrade issues on clusters with 3 workers.
* Resolves [CASMINST-4757](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4757)
Validated that upgrades worked on a 3 worker node cluster and that changing the replicas to 4 caused the 4th replicas to get stuck in pending due to requiredDuringSchedulingIgnoredDuringExecution.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?  N

CASMINST-4757 Add required pod antiaffinity

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-admin.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-user.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-admin_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-user_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.rego.tpl

Add OPA rules for SMA telemetry API and monitoring app access for the read-only monitoring role.
* Resolves [CASMPET-5664](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5664)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`
* `mug`
Made sure that a user with read-only monitoring role can log into Grafana UI and have access to telemetry API.
- Were continuous integration tests run? If not, …

CASMPET-5664: Add rules for read-only monitoring role

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-admin.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-user.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/tests/opa/Dockerfile
kubernetes/cray-opa/tests/opa/run_tests/run_tests.go
kubernetes/cray-opa/tests/opa/xname-disabled/Dockerfile
kubernetes/cray-opa/tests/opa/xname-disabled/run_tests/run_tests.go
kubernetes/cray-opa/tests/opa/xname-enabled/Dockerfile
kubernetes/cray-opa/tests/opa/xname-enabled/run_tests/run_tests.go
kubernetes/cray-opa/values.yaml

- Update opa-envoy to 0.42.1
- Add opa rego strict check to validate opa code is written correctly for the current version
- Fix opa code that failed the strict check
* Resolves [CASMPET-5793](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5793)
Validated pods started and didn't error. 
Further testing is needed on bare metal with all products installed.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? Y
This is a major version bump and needs to be tested on a bare metal 1.3.0 system with all products installed to validate …

CASMPET-5793 Update opa-envoy to 0.42.1

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.xname_workloads.invalid_xname.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.xname_workloads.rego.tpl
kubernetes/cray-opa/values.yaml

heartbeat is now using spire tokens by default. This disabled the spire authentication bypass for heartbeats and fixes issues with heartbeat spire access.
* Resolves [CASMPET-5835](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5835)
* `fanta`
Validated that storage nodes started heartbeating properly.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? Y
- Was downgrade tested? If not, why? N
heartbeats with xname filtering enabled needs to be tested to validate the API URLs are correct.
- [] Copyrights updated

CASMPET-5835 Enable spire for heartbeats

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-admin.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-user.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-admin_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-admin_policy_xforward_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-user_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-user_policy_xforward_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-hmn_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.xname_workloads.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_xforward_test.rego.tpl

Add a whitelist URL for gozerd, which does its own authentication using
MUNGE tokens.
Also, update the wlm role permissions with the following changes:
- The PALS API was removed, so remove the policy for it
- Replace FC API with VNID
- Add new jackaloped API for scalable startup support
- Remove unused PUT method for VNID/jackaloped
* Resolves PE-41317
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?
No known risks.

PE-41317 Add support for gozerd and jackaloped

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway-hmn.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-hmn_policy_test.rego.tpl

Allow keycloak token to be generated for hmn. The minor chart version was bumped.
* Resolves [CASMPET-5840](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5840)
* `surtur`
Upgraded the cray-opa chart, and verified (by Jeanne) that the keycloak token can now be generated for hmn:
"Getting token for hmnlb
auth.hmnlb.surtur.hpc.amslabs.hpecorp.net is reachable
Token successfully retrieved at https://auth.hmnlb.surtur.hpc.amslabs.hpecorp.net/keycloak/realms/shasta/protocol/openid-connect/token"
- Were continuous …

CASMPET-5840: whitelist keycloak for hmn

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.xname_workloads.rego.tpl

This allows the heartbeat spire JWT to have access to `/apis/hbtd/hmi/v1/params`. This is used in the cray-heartbeat.sh script to request the heartbeat warning wait timeout.
* Resolves [CASMPET-5856](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5856)
* shandy
Validated that the cray-heartbeat script could successfully request the warning timeout from `/apis/hbtd/hmi/v1/params`.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N
- Was downgrade tested? If not, why? N, not needed for this change.

CASMPET-5856 Allow heartbeat params api

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-admin.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-user.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway-hmn.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl

hmcollector access should only be available on the hmn gateway. In addition to this, source restrictions aren't possible due to our double SNAT issue and are being removed.
* Resolves [CASMPET-5827](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5827)
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Was upgrade tested? If not, why?  N, not possible to properly test without running on a fully installed CSM 1.3 system. Unit tests are sufficient to validate this change does not break any other …

CASMPET-5827 Remove unused hmcollector whitelist

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.xname_workloads.invalid_xname.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.xname_workloads.rego.tpl

This fixes an issue where the opa xname url was incorrectly set to `/apis/hmnfd/hmi/v2/subscriptions/%v/agents$` instead of `/apis/hmnfd/hmi/v2/subscriptions/%v`.
* Resolves [CASMPET-5197](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5197)
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Was upgrade tested? If not, why? N, tested locally via unit tests
- Was downgrade tested? If not, why? N , tested locally via unit tests
- Were new tests (or test issues/Jiras) created for this change? Updated …

CASMPET-5197 Fix hmnfd subscription api url

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/examples/custom-keycloak.yaml
kubernetes/cray-opa/examples/custom-spire.yaml
kubernetes/cray-opa/templates/policies/keycloak-admin.yaml
kubernetes/cray-opa/templates/policies/keycloak-user.yaml
kubernetes/cray-opa/tests/kuttl/custompolicy.yaml

This changes the name for keycloak admin and keycloak methods and role objects. If these are the same then the URL filtering fails and all requests using a valid keycloak JWTs throw 503s. 
* Resolves [CASMPET-5924](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5924)
Created a user and admin keycloak user and validated requests to a few API endpoints using curl.
- Were new tests (or test …

CASMPET-5924 Fix keycloak auth

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/values.yaml

`.Values.opa.xnamePolicy.tpmProvisioner` is missing a default `false` value. This is causing the CSM pipeline to fail.
* Resolves [CASMPET-5970](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5970)
Validated by running unit tests, including kind/kuttl tests.
- Was upgrade tested? If not, why? N, Not needed
- Was downgrade tested? If not, why? N, Not needed

CASMPET-5970 Add default tpmProvisioner value

---

Makefile
kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/Makefile
kubernetes/cray-opa/templates/deployment.yaml
kubernetes/cray-opa/templates/policies/keycloak-system.yaml
kubernetes/cray-opa/tests/kuttl/deployment/00-assert.yaml
kubernetes/cray-opa/tests/opa/keycloak-system_test.rego.tpl
kubernetes/cray-opa/values.yaml

When the opa policies were broken up by use the system-pxe and system-compute policies were not moved over. This creates a new policy group, keycloak-system, that's used on the main ingress.
* Resolves [CASMINST-5400](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5400)
* fanta
Validated that system-pxe keycloak access worked after applying and that it allowed nodes to continue booting.
- Was downgrade tested? If not, why? N, not needed

CASMINST-5400 Add missing system keycloak rules

---

kubernetes/cray-opa/CHANGELOG.md
kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl

The script changed its name from bos-state-reporter to bos-reporter. The OPA policy needs to match the name of the script. Thus, it too must change.
* Resolves CASMCMS-8269
* `Shandy`
I changed the OPA policy on Shandy and test-booted a node using BOS V2. It worked.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? 
- Were continuous integration tests run? If not, why? No.
- Was upgrade tested? If not, why? No.
- Was downgrade tested? If not, why? No.
- Were new tests (or test issues/Jiras) created for this change? No.
Low

CASMCMS-8269: Change BOS policy from bos-state-reporter to bos-reporter

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-user.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-user_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.rego.tpl

CVE-2020-10770 Mitigation changes
Enabling debug logs:
```ncn-m001:/tmp # kubectl edit deployment -n opa cray-opa-ingressgateway
deployment.apps/cray-opa-ingressgateway edited
ncn-m001:/tmp # kubectl edit deployment -n opa cray-opa-ingressgateway-customer-user
deployment.apps/cray-opa-ingressgateway-customer-user edited
ncn-m001:/tmp # kubectl rollout restart -n opa deployment cray-opa-ingressgateway
deployment.apps/cray-opa-ingressgateway restarted
ncn-m001:/tmp # kubectl rollout restart -n opa deployment cray-opa-ingressgateway-customer-user
deployment.apps/cray-opa-ingressgateway-customer-user restarted
ncn-m001:/tmp # kubectl -n opa logs --tail=-1 --prefix=true -l "app.kubernetes.io/name=cray-opa-ingressgateway" | grep -A 1 request_uri
ncn-m001:/tmp # kubectl -n opa logs --tail=-1 …
```

CASMPET-6127: CVE-2020-10770 mitigation changes

---

kubernetes/cray-opa/tests/opa/Dockerfile
kubernetes/cray-opa/tests/opa/xname-disabled/Dockerfile
kubernetes/cray-opa/tests/opa/xname-enabled/Dockerfile

This change updates the docker image paths for the rego tests, allowing them to complete succesfully.
* Resolves [CASMPET-6136](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6136) 
Validated tests ran successfully
- Was upgrade tested? If not, why? N/A
- Was downgrade tested? If not, why? N/A

CASMPET-6136 Update test image paths

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.rego.tpl
kubernetes/cray-opa/values.yaml

While testing a different issue on frigg I noticed that the spire-jwks endpoint is still internal on CSM 1.3. This is supposed to use the istio ingress gateway due to a caching issue causing port exhaustion. This fixes that problem.
* Resolves  [CASMPET-6126](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6126)
* frigg
Validated ingress gateway worked and that the endpoint was set to the ingress gateway.
- Was upgrade tested? If …

CASMPET-6126 Switch jwks endpoint back to ingress gateway

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-user.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-user_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.rego.tpl

CASMPET-6128: Break/Fix - Add opa policies to address keycloak vulnerabilities for request_uri and user access to admin paths
Test logs are attached as file.
[CVE202010770MitigationTestLogs.txt](https://github.com/Cray-HPE/cray-opa/files/10114479/CVE202010770MitigationTestLogs.txt)
mug.dev.cray.com
Gateway tests were run from inside and outside of mug.
Exploit provided for CVE was tested with and without the fix.
Unit test was added into regression and tested.
The same fix is submitted for 1.2 release. The PR link is provided below for reference.
https://github.com/Cray-HPE/cray-opa/pull/71

CASMPET-6128: Break/Fix - Add opa policies to address keycloak vulnerabilities for request_uri and user access to admin paths

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-admin.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-user.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-admin_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-admin_policy_xforward_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-user_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway-customer-user_policy_xforward_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_test.xname_workloads.rego.tpl
kubernetes/cray-opa/tests/opa/ingressgateway_policy_xforward_test.rego.tpl

Maintained duplicate test policy structure.
Resolves: CASMSEC-368
Restrict accessible Keycloak application paths to a subset of those defined in Keycloak 9.0.0 OIDC endpoints (Shasta Realm), for all but requests that use the CMN LB (keyed by HTTP HOST attribute):
https://github.com/keycloak/keycloak-documentation/blob/9.0.0/securing_apps/topics/oidc/oidc-generic.adoc
The following end-points were not allowed due to lack of use cases in CSM:
* token introspection
* check session iframe
* registration endpoint
Cross-referenced requests against log traces from all istio ingress gateways on multiple systems. 
* Resolves [CASMSEC-368](https://jira-pro.its.hpecorp.net:8443/browse/CASMSEC-368)
* Change will also be needed in CSM 1.3.x ([CASMSEC-370](https://jira-pro.its.hpecorp.net:8443/browse/CA …

Restrict accessible Keycloak URIs via OPA Ingress Policy.

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-user.tpl

Found YAML indentation issue in the customer-user policy and addressed
Changes are tested in the mug. And removed extra space in the line end.
Here is o/p in vi with set list.
```
#$
allow {$
startswith(original_path, "/keycloak")$
not re_match(`^/keycloak/realms/[a-zA-Z0-9]+/protocol/openid-connect/.*request_uri=.*$`, original_path)$
}$
allow { startswith(original_path, "/vcs") }$
$
:set list
```
Chart will be installed after its generated. 
There is extra space at the end of line "startswith(original_path, "/keycloak")" which causes indentation issue in the config map.

Addressed yaml indentation issue in customer-user policy

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/policies/hmn.yaml
kubernetes/cray-opa/templates/policies/keycloak-admin.yaml
kubernetes/cray-opa/templates/policies/keycloak-system.yaml
kubernetes/cray-opa/templates/policies/keycloak-user.yaml
kubernetes/cray-opa/tests/opa/hmn_test.rego.tpl
kubernetes/cray-opa/tests/opa/keycloak-admin_test.rego.tpl
kubernetes/cray-opa/tests/opa/keycloak-system_test.rego.tpl
kubernetes/cray-opa/tests/opa/keycloak-user_test.rego.tpl

Resolves: CASMSEC-370
Restrict accessible Keycloak application paths to a subset of those defined in Keycloak 9.0.0 OIDC endpoints (Shasta Realm), for all but requests that use the CMN LB (keyed by HTTP HOST attribute):
https://github.com/keycloak/keycloak-documentation/blob/9.0.0/securing_apps/topics/oidc/oidc-generic.adoc
The following end-points were not allowed due to lack of use cases in CSM:
* token introspection
* check session iframe
* registration endpoint
Cross-referenced requests against log traces from all istio ingress gateways on multiple systems. 
As a delta to content in `release/1.3`, also ported the allow-listing in the `keycloak-system` policy/test after chatting with @kburns-hpe. 
* Resolves [CASMSEC-370](https://jira-pro.its.hpecorp.net:8443/browse/CASMSEC-370)
* …

CASMSEC-370: Restrict accessible Keycloak URIs via OPA Ingress Policy

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/examples/custom-keycloak.yaml
kubernetes/cray-opa/examples/custom-spire.yaml
kubernetes/cray-opa/templates/policies/hmn.yaml
kubernetes/cray-opa/templates/policies/keycloak-admin.yaml
kubernetes/cray-opa/templates/policies/keycloak-system.yaml
kubernetes/cray-opa/templates/policies/keycloak-user.yaml
kubernetes/cray-opa/templates/policies/spire.yaml
kubernetes/cray-opa/tests/kuttl/custompolicy.yaml
kubernetes/cray-opa/tests/opa/Dockerfile
kubernetes/cray-opa/tests/opa/run_tests/run_tests.go
kubernetes/cray-opa/tests/opa/spire_test.rego.tpl
kubernetes/cray-opa/values.yaml

This adds support for handling multiple jwks servers for spire.
* Partially Resolves [CASMPET-6279](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6279) 
* 
* surtur
Validates two spire servers were able to work concurrently.

CASMPET-6279 Add support for multiple spire servers

---

kubernetes/cray-opa/CHANGELOG.md
kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/policies/keycloak-user.yaml
kubernetes/cray-opa/templates/policies/spire.yaml
kubernetes/cray-opa/tests/opa/keycloak-user_test.rego.tpl
kubernetes/cray-opa/tests/opa/spire_test.rego.tpl

The WLM SPIRE and keycloak roles are too powerful, opening up security holes. For example, a user could shut down any compute nodes they wish if they gain access to the WLM SPIRE role through a privilege escalation attack on a compute node.
To avoid this, reduce the WLM roles' allowed API calls to only those used by currently implemented features.
* Resolves [ALT-38](https://jira-pro.its.hpecorp.net:8443/browse/ALT-38)
* Unit tests
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? No
- Were continuous integration tests run? If not, why? No
- Was upgrade tested? If not, why? No
- Was downgrade tested? If not, why? No
- Were new tests (or test issues/Jiras) created for this change? Yes
It's …

ALT-38 Nerf WLM roles

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/policies/keycloak-system.yaml

This is a bug that was introduced with patching some security holes in Keycloak. The change blocked all authenticated traffic from Nexus to Keycloak for authentication of users on Nexus. The change added some more allowed endpoints for traffic with a system-nexus token. This should also be merged into main once testing has been done.
* Resolves [CASMPET-6366](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6366)
* Drax with manual change to the config map and check.
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade …

CASMPET-6366: Allow keycloak-nexus connector (main)

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/policies/keycloak-system.yaml

This is a bug that was introduced with patching some security holes in Keycloak. The change blocked all authenticated traffic from Nexus to Keycloak for authentication of users on Nexus. The change added some more allowed endpoints for traffic with a system-nexus token. This should also be merged into main once testing has been done.
* Resolves [CASMPET-6366](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6366)
* Drax with manual change to the config map and check.
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade …

CASMPET-6366: Keycloak-Nexus integration regession

---

Makefile
kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/_policy-ingressgateway-customer-user.tpl
kubernetes/cray-opa/templates/_policy-ingressgateway.tpl

Remove whitespace (spaces) from policy to have it render cleanly in configmaps. 
This doesn't impact functionality, but not having the fix will make editing the policies harder by administrators/developers. 
Add simple whitespace linting to Makefile to avoid issue in the future.
Resolves: CASMSEC-372
See Also: CASMSEC-368
Remove whitespace (spaces) from policy to have it render cleanly in configmaps. 
This doesn't impact functionality, but not having the fix will make editing the policies harder by administrators/developers. 
Add simple whitespace linting to Makefile to avoid issue in the future.
* Resolves [CASMSEC-372](https://jira-pro.its.hpecorp.net:8443/browse/CASMSEC-372)
* Change will also be needed in release/1.3 and main
(fanta)
1. Ran NCN gateway test (1.2.2)
2. Manually …

Remove whitespace (spaces) from policy to have it render cleanly in configmaps

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/policies/hmn.yaml
kubernetes/cray-opa/templates/policies/keycloak-admin.yaml
kubernetes/cray-opa/templates/policies/keycloak-system.yaml
kubernetes/cray-opa/templates/policies/keycloak-user.yaml
kubernetes/cray-opa/tests/opa/hmn_test.rego.tpl
kubernetes/cray-opa/tests/opa/keycloak-admin_test.rego.tpl
kubernetes/cray-opa/tests/opa/keycloak-system_test.rego.tpl
kubernetes/cray-opa/tests/opa/keycloak-user_test.rego.tpl

Restrict accessible Keycloak application paths to a subset of those defined in Keycloak 9.0.0 OIDC endpoints (Shasta Realm), for all but requests that use the CMN LB (keyed by HTTP HOST attribute):
https://github.com/keycloak/keycloak-documentation/blob/9.0.0/securing_apps/topics/oidc/oidc-generic.adoc
The following end-points were not allowed due to lack of use cases in CSM:
* token introspection
* check session iframe
* registration endpoint
Cross-referenced requests against log traces from all istio ingress gateways on multiple systems. 
* Resolves [CASMSEC-384](https://jira-pro.its.hpecorp.net:8443/browse/CASMSEC-384)
* Change already  in CSM 1.2.2 ([CASMSEC-368](https://jira-pro.its.hpecorp.net:8443/browse/CASMSEC-368)), 1.3.1 …

CASMSEC-384: Restrict accessible Keycloak URIs via OPA Ingress Policy

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/policies/spire.yaml
kubernetes/cray-opa/tests/opa/spire_test.rego.tpl
kubernetes/cray-opa/tests/opa/spire_xname_test.rego.tpl

This fixes the endpoint for the TPM-Provisioner server api to be the correct endpoint for the authorize endpoints
* Resolves [CASMPET-6800](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6800)
* Baldar
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) …

CASMPET-6800: Update endpoints for TPM

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/policies/keycloak-user.yaml
kubernetes/cray-opa/tests/opa/keycloak-user_test.rego.tpl

To implement the the PBS provisioning feature for the UK Met office, PBS must be able to create BOS sessions to boot nodes using specific BOS session templates. Add the endpoints needed to create a BOS v2 session and check on its progress to the wlm role.
* Resolves [ALT-683](https://jira-pro.it.hpe.com:8443/browse/ALT-683)
Tested by running unit tests.
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? No
- Were continuous integration tests run? If not, why? No
- Was upgrade tested? If not, why? No
- Was downgrade tested? If not, why? No
- Were new tests (or test issues/Jiras) created for this change? Yes
If the wlm role's client secret is leaked, attackers could shutdown or reboot …

ALT-683 Allow wlm role to create BOS sessions

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/values.yaml

A previous 1.3.1 fix for CASMPET-6126 was not merged to later releases, causing OPA pod port exhaustion in large systems. This PR adds the previous 1.3.1 fix to CSM 1.4 release.
* Resolves [CAST-34306](https://jira-pro.it.hpe.com:8443/browse/CAST-34306)
* UKMet
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade …

CAST-34306: avoid OPA pod port exhaustion

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/policies/spire.yaml
kubernetes/cray-opa/tests/opa/spire_test.rego.tpl

The DRC2 feature uses a new "ogopogod" API with SPIRE. Add this to the OPA policy to enable this feature.
* Resolves [ALT-828](https://jira-pro.it.hpe.com:8443/browse/ALT-828)
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? No
- Were continuous integration tests run? If not, why? No
- Was upgrade tested? If not, why? No
- Was downgrade tested? If not, why? No
- Were new tests (or test issues/Jiras) created for this change? Yes
If the WLM SPIRE client secret is leaked, the attacker will be able to configure DRC2 VNIs on the system. This can be mitigated by revoking and regenerating the WLM client secret.

ALT-828 Allow DRC2 calls with SPIRE

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/values.yaml

Due to the CPU limit set, some customers ran into 503 UAEX errors in a scale environment because OPA could not handle lots of simultaneous requests due to CPU throttling. This PR removes CPU limit for cray-opa to avoid this issue.
* Resolves [CASMPET-6883](https://jira-pro.it.hpe.com:8443/browse/CASMPET-6883)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`
* by NERSC
_How were the changes tested and success verified? If schema changes were part of this …

CASMPET-6883: remove CPU limit

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/policies/spire.yaml
kubernetes/cray-opa/tests/opa/spire_test.rego.tpl

Adding policies for SLS under DVS to allow the dvs_generate_map script to use the data from SLS to generate the node map.
Tested the change by editing the opa-policy-ingressgateway-spire config map and restarting pods. Verified that the SLS data is sent via the API when using a new valid token.
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
This PR pertains to new feature development to use SLS in the dvs_generate_map CSM script. Previously the script generates the DVS node map by doing host lookups for all nodes, causing a large increase in traffic at boot time. By sending only a few requests to SLS to get IP addresses instead, this greatly reduces the network traffic.
_Is this change backwards incompatible, …

DVS-2961: Allow System Layout Service calls to generate the DVS node map

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/daemonset.yaml
kubernetes/cray-opa/templates/service.yaml
kubernetes/cray-opa/tests/opa/Dockerfile
kubernetes/cray-opa/values.yaml

Due to limitations of server-side load balancing in kubernetes, especially with OPA as it uses GRPC protocol leveraging persistent connections, we often run into situations where only 1 or 2 OPA ingressgateway pods are used. This has exposed OPA memory leakage bug found in older OPA envoy plugin versions. This PR attempts to address the issue by changing OPA deployment to daemonset and uses a kubernetes beta feature that improves load balancing, in addition to using a newer OPA envoy plugin version v0.62.0 that has fixes for a memory leakage issue (https://github.com/open-policy-agent/opa/issues/5320).
* Resolves [CASMPET-6915](https://jira-pro.it.hpe.com:8443/browse/CASMPET-69 …

CASMPET-6915: use newer plugin image and change it to daemonset

---

kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/policies/hmn.yaml
kubernetes/cray-opa/templates/policies/keycloak-admin.yaml
kubernetes/cray-opa/templates/policies/keycloak-system.yaml
kubernetes/cray-opa/templates/policies/keycloak-user.yaml
kubernetes/cray-opa/tests/opa/hmn_test.rego.tpl
kubernetes/cray-opa/tests/opa/keycloak-admin_test.rego.tpl
kubernetes/cray-opa/tests/opa/keycloak-system_test.rego.tpl
kubernetes/cray-opa/tests/opa/keycloak-user_test.rego.tpl
kubernetes/cray-opa/tests/opa/run_tests/run_tests.go

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
The PR is about migrate the Slingshot 2.2.0 HPCM/Baremetal FM RBAC policy into CSM. 
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_
The feature is supported from CSM 1.6 and above. 
* Resolves [issue id](issue link) : n/a
* Change will also be needed in `<insert branch name here>` release/csm-1.6
* Future work required by [issue id](issue link) : n/a
* Documentation changes required in [issue id](issue link) : n/a
* Merge with/before/after `<insert PR URL here>`
_List the environments in which these …

SSHOTCP-7294 Migrate the Slingshot 2.2.0 HPCM/Baremetal FM RBAC policy into CSM

---

kubernetes/cray-opa/CHANGELOG.md
kubernetes/cray-opa/Chart.yaml
kubernetes/cray-opa/templates/policies/keycloak-admin.yaml
kubernetes/cray-opa/tests/opa/keycloak-admin_test.rego.tpl

Add OPA policies for tenant admins to CRUD CFS configurations (v3 endpoint only).
Add corresponding tests.
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_
* Resolves [CASMCMS-9239](issue link)
* This change should be released with the work being done in CASMCMS-9228.
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`
* `tyr`
I created a tenant 'vcluster-green' through TAPMS and created and assigned a …

CASMCMS-9239: Add OPA policies for tenant admins to CRUD CFS configurations
